### ISSUE TITLE
qv2ray 3.0 seems can't use with cgproxy

### ISSUE THREAD

**Issue by TakoTakoo** [Shadowsocks-NET/Qv2ray#3] opened 2021-06-26 03:26 UTC
When start cgproxy service. v2ray crashed. 

![2021-06-26_11-22](https://user-images.githubusercontent.com/85894051/123500507-2415f780-d671-11eb-9494-cf4130262e6b.png)

And I read the Core log with "switch to Core log", but it seems noting useful.

When I stop cgproxy, everything goes well.
And when I use Qv2ray/Qv2ray 2.7 or 2.6.3, it works well with cgproxy.

Arch Linux, latest related libraries.

**Comment by database64128** [comment] 2021-06-26 04:54
Are you using my [AUR package](https://aur.archlinux.org/packages/qv2ray-git/)? Can you post the content of `~/.config/qv2ray/generated/config.gen.json` and `/etc/cgproxy/config.json` with sensitive information redacted?

**Comment by TakoTakoo** [comment] 2021-06-26 09:51
Yes, I use your AUR package.

~/.config/qv2ray/generated/config.gen.json  

https://paste.ubuntu.com/p/dykqcxXgHd/

/etc/cgproxy/config.json

https://paste.ubuntu.com/p/ksPcQGBND7/

**Comment by database64128** [comment] 2021-06-26 12:35
Your config files should work just fine. I was not able to reproduce with a similar config. Can you run `sudo v2ray -c ~/.config/qv2ray/generated/config.gen.json` and paste the output?

**Comment by TakoTakoo** [comment] 2021-06-26 12:49
@database64128 

https://paste.ubuntu.com/p/HCpVgwvB7n/

 nil pointer？

**Comment by xiaokangwang** [comment] 2021-06-28 16:07
This issue have been addressed in 
https://github.com/v2fly/v2ray-core/commit/cf3688729e7ddc5c022c596606ed75612fa91a52 .

The root issue is that poolSize must not be empty: core does not try to figure out the correct poolSize, you need to input it yourself.

Previously, the core will just ignore settings that do not have a poolSize, lead to this confusing bug. In the future, it will show an error explicitly.

**Comment by database64128** [comment] 2021-06-28 16:20
Thank you for the quick fix @xiaokangwang.

The fix at Qv2ray side is not likely to land in this repo. The new upstream [moodyhunter/QvPersonal](https://github.com/moodyhunter/QvPersonal) should be ready for packaging in a few hours. The AUR package will be updated to use the new upstream repo. Stay tuned for updates.

**Comment by TakoTakoo** [comment] 2021-06-29 03:00
> Thank you for the quick fix @xiaokangwang.
> 
> The fix at Qv2ray side is not likely to land in this repo. The new upstream [moodyhunter/QvPersonal](https://github.com/moodyhunter/QvPersonal) should be ready for packaging in a few hours. The AUR package will be updated to use the new upstream repo. Stay tuned for updates.

What does that mean? This repo deprecated again?

**Closed** 2021-07-28 04:37 UTC
